#---------------Libraries-------------- (Step 1)
library(finalfit)
library(Hmisc)
library(dplyr)
library(ggplot2)
library(tibble)
library(readxl)
library(data.table)
library(lubridate)
library(eeptools) 
library(zoo)
library(magrittr)
library(tibble)
library(compareGroups)
library(data.table)
library(qwraps2)
library(readxl)
library(plyr)
library(xlsxjars)
library(rJava)
library(psych)
library(gdata)
#---------------Loading Data---------- (Step 2)
DAP <- read_excel("Demographics-Apnoea.xlsx")
DCO <- read_excel("Demographics-Control.xlsx")
QU <- read_excel("Questionnaire.xlsx")
Temp <- read_excel("Temp.xlsx")
