#---------------Libraries-------------- (Step 1)
library(finalfit)
library(Hmisc)
library(dplyr)
library(ggplot2)
library(tibble)
library(readxl)
library(data.table)
library(lubridate)
library(eeptools) 
library(zoo)
library(magrittr)
library(tibble)
library(compareGroups)
library(data.table)
library(qwraps2)
library(readxl)
library(plyr)
library(xlsxjars)
library(rJava)
library(psych)
#---------------Loading Data---------- (Step 2)
Dem5 <- read_excel("~/Desktop/Hessa Al-Jarrallah/Demographics (Control)/Demographics (Control) new.xlsx")
